[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "oldest-supported-numpy"]
build-backend = 'setuptools.build_meta'

[tool.cibuildwheel.macos]
skip = "pp*"

[tool.cibuildwheel.windows]
skip = "pp*"

[tool.cibuildwheel.linux.environment]
CC = "gcc"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add clang"
environment = { CC="clang" }
