[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "oldest-supported-numpy;python_version<'3.9'",
            "numpy>=1.25;python_version>='3.9'"]
build-backend = 'setuptools.build_meta'

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]

[tool.cibuildwheel.macos]
skip = "pp*"
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.windows]
skip = "pp*"

[tool.cibuildwheel.linux.environment]
CC = "gcc"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add clang"
environment = { CC="clang" }
