[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "oldest-supported-numpy"]
build-backend = 'setuptools.build_meta'

[tool.cibuildwheel]
skip = "pp* *-musllinux*"
